### ISSUE TITLE
urls linked to "bls20AWS/Auth0EventBridge" instead of "aws-samples/amazon-eventbridge-integration-with-auth0"

### ISSUE THREAD

**Issue by sbendzus** [aws-samples/amazon-eventbridge-integration-with-auth0#1]
I guess you moved your repo from bls20aws to aws-samples and forget to correct the urls
in:
README.md
guides/Quide_QuickSight_Visuals.md
guides/Quide_QuickSight_Visuals2.md
guides/Guide_QuickSight_S3_Permissions.md

**Comment by benjasl-stripe** [comment]
resolved back in October but forgot to mark this
